import pygame

pygame.init()

wall_surf = pygame.image.load("pictures/wall.png")
tile_surf = pygame.image.load("pictures/tile.png")
entrance_surf = pygame.image.load("pictures/entrance.png")
exit_surf = pygame.image.load("pictures/exit.png")
grid_surf = pygame.image.load("pictures/grid.png")
player_surf = pygame.image.load("pictures/player.png")
monster_surf = pygame.image.load("pictures/monster.png")
boss_surf = pygame.image.load("pictures/boss.png")
coin_surf = pygame.image.load("pictures/coin.png")
health_surf = pygame.image.load("pictures/health.png")
chest_surf = pygame.image.load("pictures/chest.png")
shop_surf = pygame.image.load("pictures/shop.png")
black_surf = pygame.image.load("pictures/black.png")
mask_surf = pygame.image.load("pictures/mask.png")
maze_surf = pygame.image.load("pictures/maze.png")
rat_surf = pygame.image.load("pictures/rat.png")
tree_surf = pygame.image.load("pictures/tree.png")
rusty_dagger_surf = pygame.image.load("pictures/rusty_dagger.png")
oak_staff_surf = pygame.image.load("pictures/oak_staff.png")
iron_mace_surf = pygame.image.load("pictures/iron_mace.png")
steel_sword_surf = pygame.image.load("pictures/steel_sword.png")
shadow_blade_surf = pygame.image.load("pictures/shadow_blade.png")
flame_axe_surf = pygame.image.load("pictures/flame_axe.png")
lightning_spear_surf = pygame.image.load("pictures/lightning_spear.png")
crystal_wand_surf = pygame.image.load("pictures/crystal_wand.png")
venom_dagger_surf = pygame.image.load("pictures/venom_dagger.png")
rune_staff_surf = pygame.image.load("pictures/rune_staff.png")
holy_hammer_surf = pygame.image.load("pictures/holy_hammer.png")
dragon_lance_surf = pygame.image.load("pictures/dragon_lance.png")
right_hand = (rusty_dagger_surf, oak_staff_surf, iron_mace_surf, steel_sword_surf, shadow_blade_surf, flame_axe_surf,
              lightning_spear_surf, crystal_wand_surf, venom_dagger_surf, rune_staff_surf, holy_hammer_surf,
              dragon_lance_surf)
wooden_buckler_surf = pygame.image.load("pictures/wooden_buckler.png")
iron_shield_surf = pygame.image.load("pictures/iron_shield.png")
bull_shield_surf = pygame.image.load("pictures/bull_shield.png")
light_barrier_surf = pygame.image.load("pictures/light_barrier.png")
crystal_tower_surf = pygame.image.load("pictures/crystal_tower.png")
turtle_shield_surf = pygame.image.load("pictures/turtle_shield.png")
golden_barrier_surf = pygame.image.load("pictures/golden_barrier.png")
flame_aegis_surf = pygame.image.load("pictures/flame_aegis.png")
rune_engraved_surf = pygame.image.load("pictures/rune_engraved.png")
holy_aegis_surf = pygame.image.load("pictures/holy_aegis.png")
left_hand = (wooden_buckler_surf, iron_shield_surf, bull_shield_surf, light_barrier_surf, crystal_tower_surf,
             turtle_shield_surf, golden_barrier_surf, flame_aegis_surf, rune_engraved_surf, holy_aegis_surf)

pygame.mixer.music.load("sounds/menu.wav")
grid_open_sound = pygame.mixer.Sound("sounds/grid_open.wav")
grid_slam_sound = pygame.mixer.Sound("sounds/grid_slam.wav")
steps_sound = pygame.mixer.Sound("sounds/steps.wav")
coin_sound = pygame.mixer.Sound("sounds/coin.wav")
chest_sound = pygame.mixer.Sound("sounds/chest.wav")
health_sound = pygame.mixer.Sound("sounds/health.wav")
monster_sound = pygame.mixer.Sound("sounds/monster.wav")
boss_sound = pygame.mixer.Sound("sounds/boss.wav")
shop_sound = pygame.mixer.Sound("sounds/shop.wav")
new_level_sound = pygame.mixer.Sound("sounds/new_level.wav")
rat_sound = pygame.mixer.Sound("sounds/rat.wav")
chop_sound = pygame.mixer.Sound("sounds/chop.wav")

normal_font = pygame.font.Font(None, 23)
highlighted_font = pygame.font.Font(None, 26)
menu_font = pygame.font.Font(None, 40)
